theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
- jekyll-seo-tag
- jemoji
title: Sepsis MAIC
description: Analysis of implicated host genes in adult sepsis using the MAIC algorithm